import React from 'react';
import { Button, Card, Empty, Form, Input, Modal, Select, Space, Table, Tabs, Tag, message } from 'antd';
import { ArrowRight, CheckCircle2, FileText, Flag, Search, ShieldCheck, XCircle } from 'lucide-react';

export const TRIAL_STORAGE_KEY = 'mmos.trial.records';
const seedTrials = [
  { key: 'trial-001', projectNo: 'ZJ20260912006', projectName: '语音质检专项', customer: '字节', pm: '林晓彤', taskType: 'ASR/TTS', startDate: '2026-09-18', status: '试标中', brief: '完成语音质检样本评测与质量指标验证', docs: 'https://feishu.cn/docx/trial-001', review: '', updatedAt: '2026-09-20 16:20', activity: ['2026-09-20 16:20 · PMO通过立项申请，项目进入试标中'] },
  { key: 'trial-002', projectNo: 'ZJ20260916017', projectName: '中文答案可用性评测', customer: '字节', pm: '王然', taskType: '评测', startDate: '2026-09-20', status: '试标中', brief: '验证中文答案可用性评测标准和样例', docs: 'https://feishu.cn/docx/trial-002', review: '', updatedAt: '2026-09-20 15:36', activity: ['2026-09-20 15:36 · PMO通过立项申请，项目进入试标中'] },
  { key: 'trial-003', projectNo: 'ZJ20260909012', projectName: '海外客服意图识别', customer: '腾讯', pm: '王然', taskType: '文本分类', startDate: '2026-09-12', status: '试标成功', brief: '完成海外客服意图分类试标', docs: 'https://feishu.cn/docx/trial-003', review: '客户确认样例通过，已进入报价阶段', updatedAt: '2026-09-19 11:10', activity: ['2026-09-19 11:10 · 王然提交试标成功，项目进入报价阶段'] },
  { key: 'trial-004', projectNo: 'ZJ20260907004', projectName: '电商图像质检试标', customer: '京东', pm: '林晓彤', taskType: '图像', startDate: '2026-09-08', status: '试标失败', brief: '完成电商图像质检样例验证', docs: 'https://feishu.cn/docx/trial-004', review: '样本一致性未达到客户要求，已提交失败复盘资料', updatedAt: '2026-09-18 18:42', failureReason: '样本标注一致性不足', retrospective: '问题集中在边界样本定义不清，已补充标注规范并记录改进动作。', activity: ['2026-09-18 18:42 · 林晓彤提交试标失败及复盘资料'] },
];

function loadTrials() { try { const value = localStorage.getItem(TRIAL_STORAGE_KEY); return value ? JSON.parse(value) : seedTrials; } catch { return seedTrials; } }
function persistTrials(next) { localStorage.setItem(TRIAL_STORAGE_KEY, JSON.stringify(next)); window.dispatchEvent(new CustomEvent('mmos:trial-updated', { detail: next })); }

const statusColor = { '试标中': 'processing', '试标成功': 'success', '试标失败': 'error' };
function TrialStatus({ status }) { return <Tag color={statusColor[status] || 'default'}>{status}</Tag>; }

function TrialDetail({ record, onClose, canOperate, onSuccess, onFailure }) {
  return <div className="detail-screen"><div className="detail-screen-bar"><div className="detail-screen-main"><button className="detail-back" onClick={onClose}>返回列表</button><div className="detail-screen-kicker">试标管理 · {record?.projectNo}</div><h1>{record?.projectName}</h1></div>{record?.status === '试标中' && canOperate && <Space className="detail-screen-actions"><Button type="primary" icon={<CheckCircle2 size={15} />} onClick={() => onSuccess(record)}>试标成功</Button><Button danger icon={<XCircle size={15} />} onClick={() => onFailure(record)}>试标失败</Button></Space>}</div>
    {record && <><div className="trial-detail-meta"><TrialStatus status={record.status} /><span>客户：{record.customer}</span><span>PM：{record.pm}</span><span>起始日期：{record.startDate}</span></div><section className="trial-detail-hero"><div><small>试标目标</small><strong>{record.brief}</strong></div><div><small>任务类型</small><strong>{record.taskType}</strong></div><div><small>相关文档</small><a href={record.docs} target="_blank" rel="noreferrer">查看试标文档</a></div></section><section className="trial-detail-section"><div className="trial-detail-heading"><div><p className="panel-kicker">试标结果</p><h3>{record.status === '试标中' ? '等待 PM 操作' : record.status}</h3></div></div>{record.review && <div className="trial-review-box">{record.review}</div>}{record.status === '试标失败' && <div className="trial-failure-box"><strong>失败复盘资料</strong><p><b>失败原因：</b>{record.failureReason}</p><p><b>复盘内容：</b>{record.retrospective}</p></div>}</section><section className="trial-detail-section"><div className="trial-detail-heading"><div><p className="panel-kicker">操作留痕</p><h3>试标动态</h3></div></div><div className="init-activity">{record.activity?.map(item => <div key={item}><span /><p>{item}</p></div>)}</div></section></>}
  </div>;
}

function FailureModal({ record, open, onCancel, onSubmit }) { const [form] = Form.useForm(); return <Modal title={<span><XCircle size={16} /> 提交试标失败复盘</span>} open={open} onCancel={onCancel} okText="提交失败复盘" okButtonProps={{ danger: true }} onOk={() => form.validateFields().then(values => { onSubmit(record, values); form.resetFields(); })}><p className="modal-help-copy">提交后项目状态变为“试标失败”，记录会保留在试标管理中。</p><Form form={form} layout="vertical"><Form.Item name="failureReason" label="失败原因" rules={[{ required: true, message: '请填写失败原因' }]}><Input.TextArea rows={3} placeholder="请填写客户反馈或试标未通过原因" /></Form.Item><Form.Item name="retrospective" label="失败复盘内容" rules={[{ required: true, message: '请填写失败复盘内容' }]}><Input.TextArea rows={4} placeholder="请填写问题分析、改进动作和后续建议" /></Form.Item><Form.Item name="docs" label="复盘资料链接"><Input placeholder="粘贴飞书文档或附件链接" /></Form.Item></Form></Modal>; }

export function TrialPage({ role = 'PMO', onRoleChange }) {
  const [records, setRecords] = React.useState(loadTrials);
  const [tab, setTab] = React.useState('all'); const [query, setQuery] = React.useState(''); const [selected, setSelected] = React.useState(null); const [failureRecord, setFailureRecord] = React.useState(null);
  React.useEffect(() => { const sync = event => event.detail && setRecords(event.detail); window.addEventListener('mmos:trial-updated', sync); return () => window.removeEventListener('mmos:trial-updated', sync); }, []);
  const visible = records.filter(item => role === 'PMO' || item.pm === '王然').filter(item => tab === 'all' || item.status === tab).filter(item => !query.trim() || [item.projectNo, item.projectName, item.customer, item.pm].some(value => String(value).includes(query.trim())));
  const update = (record, patch) => { const next = records.map(item => item.key === record.key ? { ...item, ...patch, updatedAt: '2026-09-21 10:20' } : item); persistTrials(next); setRecords(next); setSelected(null); };
  const markSuccess = record => { update(record, { status: '试标成功', review: 'PM已确认试标通过，项目已进入报价阶段', activity: [`2026-09-21 10:20 · ${record.pm}提交试标成功，项目进入报价阶段`, ...(record.activity || [])] }); message.success('试标成功，项目已进入报价阶段'); };
  const markFailure = (record, values) => { update(record, { ...values, status: '试标失败', activity: [`2026-09-21 10:20 · ${record.pm}提交试标失败及复盘资料`, ...(record.activity || [])] }); setFailureRecord(null); message.success('试标失败复盘已提交'); };
  const rowsByStatus = status => records.filter(item => role === 'PMO' || item.pm === '王然').filter(item => !status || item.status === status).length;
  const columns = [{ title: '项目编号', dataIndex: 'projectNo', width: 140, render: value => <span className="trial-project-no">{value}</span> }, { title: '项目名称', dataIndex: 'projectName', width: 220, render: (value, record) => <button className="trial-name-link" onClick={() => setSelected(record)}><span className="trial-name-icon"><FileText size={14} /></span><span><strong>{value}</strong><small>{record.customer} · {record.pm}</small></span></button> }, { title: '客户', dataIndex: 'customer', width: 100 }, { title: 'PM', dataIndex: 'pm', width: 80 }, { title: '任务类型', dataIndex: 'taskType', width: 100 }, { title: '试标状态', dataIndex: 'status', width: 110, render: value => <TrialStatus status={value} /> }, { title: '更新时间', dataIndex: 'updatedAt', width: 150 }, { title: '操作', key: 'action', width: 210, render: (_, record) => <Space size={4}><Button type="link" size="small" onClick={() => setSelected(record)}>查看详情</Button>{role === 'PM' && record.status === '试标中' && <><Button type="link" size="small" onClick={() => markSuccess(record)}>试标成功</Button><Button danger type="link" size="small" onClick={() => setFailureRecord(record)}>试标失败</Button></>}</Space> }];
  const items = [{ key: 'all', label: <span>全部 <em>{rowsByStatus()}</em></span> }, { key: '试标中', label: <span>试标中 <em>{rowsByStatus('试标中')}</em></span> }, { key: '试标成功', label: <span>试标成功 <em>{rowsByStatus('试标成功')}</em></span> }, { key: '试标失败', label: <span>试标失败 <em>{rowsByStatus('试标失败')}</em></span> }];
  if (selected) return <div className="trial-page"><TrialDetail record={selected} onClose={() => setSelected(null)} canOperate={role === 'PM'} onSuccess={markSuccess} onFailure={record => setFailureRecord(record)} /><FailureModal record={failureRecord} open={Boolean(failureRecord)} onCancel={() => setFailureRecord(null)} onSubmit={markFailure} /></div>;
  return <div className="trial-page"><div className="trial-page-heading"><div><p className="eyebrow">项目管理 · 试标管理</p><h1>试标管理</h1><p className="subtitle">PMO 查看全部试标记录，PM 处理自己负责项目的试标结果。</p></div><Space><div className="trial-role-switch"><ShieldCheck size={14} /><span>演示身份</span><Select size="small" value={role} onChange={onRoleChange} options={[{ value: 'PMO', label: 'PMO · 林晓彤' }, { value: 'PM', label: 'PM · 王然' }, { value: '财务', label: '财务 · 赵敏' }]} /></div></Space></div><RowStats records={records} role={role} /><Card bordered={false} className="trial-work-card"><div className="trial-list-toolbar"><Space><Input prefix={<Search size={15} />} allowClear value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索项目名称、编号、客户、PM" /></Space><span className="trial-permission-chip"><ShieldCheck size={13} /> {role === 'PMO' ? '全部试标记录' : '我的试标记录'}</span></div><Tabs activeKey={tab} onChange={setTab} items={items} className="trial-tabs" /><div className="trial-table-wrap"><Table rowKey="key" columns={columns} dataSource={visible} pagination={{ pageSize: 8, showSizeChanger: false }} scroll={{ x: 1100 }} locale={{ emptyText: <Empty description="暂无符合条件的试标记录" /> }} /></div></Card></div>;
}

function RowStats({ records, role }) { const visible = records.filter(item => role === 'PMO' || item.pm === '王然'); return <div className="trial-stat-grid"><Card bordered={false}><div><small>试标中</small><strong>{visible.filter(item => item.status === '试标中').length}</strong></div></Card><Card bordered={false}><div><small>试标成功</small><strong>{visible.filter(item => item.status === '试标成功').length}</strong></div></Card><Card bordered={false}><div><small>试标失败</small><strong>{visible.filter(item => item.status === '试标失败').length}</strong></div></Card></div>; }
