import React from 'react';
import { createRoot } from 'react-dom/client';
import { getPageTitle, Sidebar, Topbar, PlaceholderPage } from './components/AppShell';
import { OverviewPage } from './components/OverviewPage';
import { RequirementsPage } from './components/RequirementsPage';
import { ProjectMasterPage } from './components/ProjectMasterPage';
import { getInitiationApplications, InitiationPage } from './components/InitiationPage';
import { TodoPage } from './components/TodoPage';
import { TrialPage } from './components/TrialPage';
import { isQuoteTodo, QuotationPage } from './components/QuotationPage';
import { AcceptancePage, isAcceptanceTodo } from './components/AcceptancePage';
import { InvoiceLedgerPage, loadInvoices } from './components/InvoiceLedgerPage';
import './styles.css';

function readQuotes() { try { return JSON.parse(localStorage.getItem('mmos.quotation.records.v3') || '[]'); } catch { return []; } }
function readAcceptance() { try { return JSON.parse(localStorage.getItem('mmos.acceptance.records.v1') || '[]'); } catch { return []; } }
function countTodos(role) { if (role === '财务') return loadInvoices().filter(item => item.invoiceStatus === '待开票').length; const initiation = getInitiationApplications().filter(item => role === 'PMO' ? item.status === '待 PMO 审核' : item.creator === '王然' && ['草稿', '审核不通过'].includes(item.status)).length; return initiation + readQuotes().filter(item => isQuoteTodo(item, role)).length + readAcceptance().filter(item => isAcceptanceTodo(item, role)).length; }
function App() { const initial = new URLSearchParams(window.location.search).get('page') || 'overview'; const [active, setActive] = React.useState(initial.startsWith('quotation') ? 'quotation' : initial.startsWith('acceptance') ? 'acceptance' : initial); const [quoteFocus, setQuoteFocus] = React.useState(initial.startsWith('quotation:') ? initial.split(':')[1] : ''); const [acceptancePreset, setAcceptancePreset] = React.useState(null); const [mobileOpen, setMobileOpen] = React.useState(false); const [role, setRole] = React.useState('PMO'); const [todoCount, setTodoCount] = React.useState(() => countTodos('PMO')); const refreshTodos = nextRole => setTodoCount(countTodos(nextRole)); React.useEffect(() => { const sync = () => refreshTodos(role); window.addEventListener('mmos:initiation-updated', sync); window.addEventListener('mmos:quotation-updated', sync); window.addEventListener('mmos:acceptance-updated', sync); window.addEventListener('mmos:invoice-updated', sync); return () => { window.removeEventListener('mmos:initiation-updated', sync); window.removeEventListener('mmos:quotation-updated', sync); window.removeEventListener('mmos:acceptance-updated', sync); window.removeEventListener('mmos:invoice-updated', sync); }; }, [role]); const navigate = id => { const [pageId, projectId, projectNo] = String(id).split(':'); setActive(pageId); setQuoteFocus(pageId === 'quotation' ? projectId || '' : ''); setAcceptancePreset(pageId === 'acceptance' && projectId ? { projectId, projectNo } : null); window.history.replaceState(null, '', `?page=${pageId}`); setMobileOpen(false); }; const changeRole = next => { setRole(next); refreshTodos(next); }; const page = active === 'overview' ? <OverviewPage /> : active === 'requirements' ? <RequirementsPage /> : active === 'projects' ? <ProjectMasterPage role={role} onRoleChange={changeRole} onNavigate={navigate} /> : active === 'initiation' ? <InitiationPage role={role} onRoleChange={changeRole} /> : active === 'trial' ? <TrialPage role={role} onRoleChange={changeRole} /> : active === 'quotation' ? <QuotationPage role={role} onRoleChange={changeRole} focusKey={quoteFocus} /> : active === 'acceptance' ? <AcceptancePage role={role} onRoleChange={changeRole} presetProject={acceptancePreset} onPresetHandled={() => setAcceptancePreset(null)} /> : active === 'invoice-ledger' ? <InvoiceLedgerPage role={role} onRoleChange={changeRole} /> : active === 'todos' ? <TodoPage role={role} onRoleChange={changeRole} onNavigate={navigate} /> : <PlaceholderPage title={getPageTitle(active)} />; return <div className="app-shell"><Sidebar active={active} role={role} mobileOpen={mobileOpen} onNavigate={navigate} onClose={() => setMobileOpen(false)} /><main className="main-area"><Topbar active={active} todoCount={todoCount} onMenu={() => setMobileOpen(true)} onTodo={() => navigate('todos')} /><div className="content-wrap">{page}</div></main></div> }

createRoot(document.getElementById('root')).render(<App />);

